repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: master
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./mymodule/path"]